"""increase password_hash length

Revision ID: 31083f0d463c
Revises: 919ff05b5023
Create Date: 2026-03-15 15:13:34.810871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31083f0d463c'
down_revision = '919ff05b5023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
