"""add index on expenses user_id and date

Revision ID: 46ef446c1a29
Revises: 31083f0d463c
Create Date: 2026-04-10 11:23:16.418951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ef446c1a29'
down_revision = '31083f0d463c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.create_index('ix_expense_user_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_index('ix_expense_user_date')

    # ### end Alembic commands ###
